### ISSUE TITLE
Doubts while selecting attributes based on index

### ISSUE THREAD

**Issue by im403** [psyclone20/k-means-clustering#1]
as i m struck on selecting the index of x and y so please do help me

**Comment by psyclone20** [comment]
Hey Praveen,
Sorry for the late reply.
The X and Y attributes are nothing but the indexes of the data attributes in the input CSV file. Keep in mind that these are 0-indexed.

For example, if your CSV file is of the format:
`id, first_name, last_name, age, rating`
then to cluster the data using `age` vs `rating`, you would enter the X attribute as 4 and Y attribute as 3.
