### ISSUE TITLE
Still pointing some error refer attached screenshots

### ISSUE THREAD

**Issue by im403** [psyclone20/k-means-clustering#2]
![ghk](https://user-images.githubusercontent.com/26847226/46619093-dcf11c80-cb3e-11e8-9121-c8ef1ca7ae1a.png)

**Comment by psyclone20** [comment]
The X and Y attributes can only be numeric. The attribute you are passing seems to be a String.
Try removing the first line of your CSV file and then running the program, since it may contain the labels of the attributes which are always Strings.
